
project_id = "lvifsxsrbluehopamqpy"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
port = 54327

[auth]
port = 54328
uri = "http://localhost:54328"

[realtime]
port = 54329

[functions.data-fetch]
verify_jwt = true
serve_custom_404 = true

[functions.data-push]
verify_jwt = true
serve_custom_404 = true

[functions.process-integration-jobs]
verify_jwt = true
serve_custom_404 = true
