
project_id = "lvifsxsrbluehopamqpy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54320

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 54322

[storage]
enabled = true

[functions]
[functions.comms-webhook-twilio]
verify_jwt = false

[functions.chat-webhook-twilio]
verify_jwt = false

[functions.test-workflow-prompt]
verify_jwt = false
