
project_id = "lvifsxsrbluehopamqpy"

[functions.email-summary]
verify_jwt = true

[functions.test-workflow-prompt]
verify_jwt = true

[functions.chat-session-manager]
verify_jwt = true

[functions.send-channel-message]
verify_jwt = true

[functions.email-webhook]
verify_jwt = false

[functions.generate-multi-project-message]
verify_jwt = true

[functions.send-multi-project-message]
verify_jwt = true
